# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.3
info:
  title: Dataset Discovery Service - OpenAPI 3.0
  description: |-
    This is the OpenAPI 3.0 specification for the Dataset Discovery Service.
    This service is responsible for dataset discovery, in the scope of Genomic Data Infrastructure (GDI).
    The service provides endpoints for searching datasets, and retrieving DCAT-AP metadata.

  #termsOfService: http://TODO/terms/
  contact:
    email: gdi-WP4@elixir-europe.org
  license:
    name: Apache 2.0
    url: https://spdx.org/licenses/Apache-2.0.html
  version: 0.0.0
externalDocs:
  description: Find out more about GDI
  url: https://genomicdatainfrastructure.github.io/gdi-userportal-docs/
servers:
  - url: https://localhost:8080
    description: Development server
paths:
  /api/v1/datasets/search:
    post:
      summary: Searches for packages based on criteria
      operationId: dataset_search
      tags:
        - "dataset-query"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DatasetSearchQuery"
      responses:
        "200":
          description: A list of datasets matching the search criteria
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetsSearchResponse"
      security:
        - discovery_auth:
            - read:datasets
  /api/v1/datasets/{id}:
    get:
      summary: Retrieves a dataset by its ID
      operationId: retrieve_dataset
      tags:
        - "dataset-query"
      parameters:
        - name: id
          in: path
          description: The ID of the dataset to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The dataset
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RetrievedDataset"
        "404":
          description: Dataset not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - discovery_auth:
            - read:datasets
components:
  securitySchemes:
    discovery_auth:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        authorizationCode:
          tokenUrl: https://api.example.com/oauth2/token
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read:datasets: read datasets
  schemas:
    DatasetSearchQuery:
      type: object
      properties:
        query:
          type: string
          title: Solr search query
        facets:
          type: array
          title: Facets
          items:
            $ref: "#/components/schemas/DatasetSearchQueryFacet"
        sort:
          type: string
          title: Sorting of search results
          default: "score desc, metadata_modified desc"
        rows:
          type: integer
          title: Max number of rows to return
          default: 10
          minimum: 0
          maximum: 1000
        start:
          type: integer
          title: Offset in the complete result set
          default: 0
          minimum: 0
        operator:
          title: Ckan query operator
          type: string
          enum:
            - AND
            - OR
          default: OR
    DatasetSearchQueryFacet:
      type: object
      properties:
        facetGroup:
          type: string
          title: Facet group
        facet:
          type: string
          title: Facet
        value:
          type: string
          title: Value
    SearchedDataset:
      type: object
      properties:
        id:
          type: string
          title: Identifier
        identifier:
          type: string
          title: Identifier
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        themes:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: Themes
        catalogue:
          type: string
          title: Catalogue
        modifiedAt:
          type: string
          format: date-time
          title: Dataset modified at
        createdAt:
          type: string
          format: date-time
          title: Metadata for dataset created at
        recordsCount:
          type: integer
          title: Records count
      required:
        - id
        - title
        - description
        - catalogue
        - modifiedAt
    DatasetsSearchResponse:
      type: object
      properties:
        count:
          type: integer
          description: The number of results found
        facetGroupCount:
          type: object
          additionalProperties:
            type: integer
        results:
          type: array
          items:
            $ref: "#/components/schemas/SearchedDataset"
        facetGroups:
          type: array
          items:
            $ref: "#/components/schemas/FacetGroup"
          description: Facet groups
    RetrievedDataset:
      type: object
      properties:
        id:
          type: string
          title: Dataset internal ID
        identifier:
          type: string
          title: Identifier
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        themes:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: Themes
        publisherName:
          type: string
          title: Publisher Name
        catalogue:
          type: string
          title: Catalogue
        createdAt:
          type: string
          format: date-time
          title: Dataset created at
        modifiedAt:
          type: string
          format: date-time
          title: Dataset modified at
        url:
          type: string
          title: Dataset URL
        languages:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: Languages
        contact:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: Contact
        creator:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: Contact
        hasVersions:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: Has Versions
        accessRights:
          $ref: "#/components/schemas/ValueLabel"
          title: Access Rights
        conformsTo:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: Conforms to
        keywords:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: Keywords
        provenance:
          type: string
          title: Contact URI
        spatial:
          $ref: "#/components/schemas/ValueLabel"
          title: Spatial
        distributions:
          type: array
          items:
            $ref: "#/components/schemas/RetrievedDistribution"
          title: Distributions
      required:
        - id
        - title
        - description
        - catalogue
        - createdAt
    RetrievedDistribution:
      type: object
      properties:
        id:
          type: string
          title: Distribution internal ID
        title:
          type: string
          title: Title
        description:
          type: string
          title: Description
        format:
          $ref: "#/components/schemas/ValueLabel"
          title: Format
        uri:
          type: string
          title: URI
        createdAt:
          type: string
          format: date-time
          title: Distribution created at
        modifiedAt:
          type: string
          format: date-time
          title: Distribution modified at
      required:
        - id
        - title
        - description
        - createdAt
    ValueLabel:
      properties:
        value:
          type: string
          title: value
        label:
          type: string
          title: label
      required:
        - value
        - label
    FacetGroup:
      properties:
        key:
          type: string
          title: Key
        label:
          type: string
          title: Label
        facets:
          type: array
          items:
            $ref: "#/components/schemas/Facet"
          title: Facets
    Facet:
      properties:
        key:
          type: string
          title: Key
        label:
          type: string
          title: Label
        values:
          type: array
          items:
            $ref: "#/components/schemas/ValueLabel"
          title: values
    ErrorResponse:
      properties:
        title:
          type: string
          title: Error title
        status:
          type: integer
          title: Error status
        detail:
          type: string
          title: Error detail
